# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: 
      - main
    
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      working-directory: ./DelidisLoginApp
      run: dotnet restore

    - name: Build
      working-directory: ./DelidisLoginApp
      run: dotnet build --configuration Release

  release:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Publish artifact
      run: dotnet publsh -c Release -r win-x64 --self-contained -o ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: DelidisLoginApp
        path:
          ./publish
          ./bin/Debug/net8.0-windows/DataFile.db
    
